Repository EthanHaque/hifz, pull requests merged in 2024-10, with the labels that each got.

#3 feat: add arabic letters data
  data/arabic_letters.csv
Labels: enhancement

#2 chore: remove ruff from dev dependencies
  README.md
  pyproject.toml
Labels: chore

#8 docs: update project configuration in README.md
  README.md
Labels: documentation

#11 refactor: rename flashcards to cards
  src/hifz/learning_strategies.py
  src/hifz/utils.py
  tests/conftest.py
  tests/test_learning_strategies.py
  tests/test_utils.py
Labels: refactor

#12 feat: json dataloading and json/csv temp data test
  .gitignore
  data/arabic_letters.json
  src/hifz/dataserver.py
  tests/test_dataserver.py
Labels: enhancement
